//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#routes
////
//// DO NOT EDIT THIS FILE. If you would like to use plain pattern
//// matching over this compiled route approach, take a look at
//// the docs link below detailing how to do so.
////
//// See: https://github.com/glimr-org/glimr?tab=readme-ov-file#direct-pattern-matching
////

import app/http/controllers/welcome_controller
import gleam/http.{Get}
import wisp

pub fn routes(path, method, _req, _ctx) {
  case path {
    [] ->
      case method {
        Get -> welcome_controller.show()
        _ -> wisp.method_not_allowed([Get])
      }

    _ -> wisp.not_found()
  }
}
