[commands]
  auto_compile = true

  packages = [
    "glimr",
    "glimr_postgres",
    "glimr_auth",
  ]

[routes]
  auto_compile = true

[loom]
  auto_compile = true

# Define any shell commands or Glimr commands you want to run
# when running the `./glimr build` command
[hooks.build]

  # Before `gleam build` logic is ran
  pre = [
    "./glimr route_compile",
    "./glimr loom_compile",
    "./glimr command_compile",
  ]

  # After `gleam build` logic is ran
  post = [
    "gleam format",
  ]

# Define any shell commands or Glimr commands you want to run
# when running the `./glimr run` command
[hooks.run]

  # Before `gleam run` logic is ran
  pre = [
    "./glimr route_compile",
    "./glimr loom_compile",
    "./glimr command_compile",
  ]

# Define any shell commands or Glimr commands you want to run
# during the `./glimr run` command, when an app reload needs 
# to occur. (When .gleam or .loom.html files are modified)
[hooks.run.reload]

  # When any .gleam or .loom.html file is modified, before
  # the app is reloaded
  pre = []

  # After all other reload hooks run, right before the 
  # actual reload occurs
  post-modified = []
