//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import compiled/loom/components/icons/frame as components_icons_frame
import compiled/loom/components/icons/reader as components_icons_reader
import compiled/loom/components/icons/star as components_icons_star
import compiled/loom/components/layouts/app as components_layouts_app
import compiled/loom/components/logo as components_logo
import glimr/loom/runtime

pub fn render() -> String {
  ""
  <> components_layouts_app.render(
    slot_meta_title: { "" <> "Glimr ✨" },
    slot_head: {
      ""
      <> "\n    <link\n      href=\"https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900\"\n      rel=\"stylesheet\"\n    />\n\n    <style>\n      @keyframes float {\n        0%,\n        100% {\n          transform: translateY(0);\n        }\n        50% {\n          transform: translateY(-10px);\n        }\n      }\n    </style>\n  "
    },
    slot_footer: "",
    slot_footer_scripts: "",
    slot: {
      ""
      <> "\n  "
      <> "\n\n  "
      <> "\n\n  <div\n    class=\"flex items-center justify-center relative h-screen bg-linear-to-br from-[#ffb8e4] via-white to-[#ffb8e4] font-['Inter'] text-[#2c2e49] antialiased\"\n  >\n    <div class=\"text-center\">\n      "
      <> components_logo.render(attributes: [
        runtime.Attribute(
          "class",
          "animate-[float_3s_ease-in-out_infinite] mb-7.5 mx-auto",
        ),
        runtime.Attribute("width", "140"),
      ])
      <> "\n\n      <div class=\"text-[17px] mb-1.25 font-medium\">Welcome to Glimr ✨</div>\n\n      <div class=\"mb-5 text-[#9ea0b7] text-[15px]\">\n        The batteries-included web framework for Gleam.\n      </div>\n\n      <div class=\"mt-5 flex items-center justify-center\">\n        <a\n          target=\"_blank\"\n          href=\"https://github.com/glimr-org/glimr?tab=readme-ov-file#glimr-\"\n          class=\"inline-flex items-center gap-1 text-[#2c2e49] mx-2.5 text-sm no-underline transition-colors duration-300 hover:text-[#ff43a1]\"\n        >\n          "
      <> components_icons_reader.render(attributes: [
        runtime.Attribute("class", "mr-px text-[#ff43a1]"),
        runtime.Attribute("width", "15"),
      ])
      <> "\n\n          Documentation\n        </a>\n        <a\n          target=\"_blank\"\n          href=\"https://github.com/glimr-org/framework\"\n          class=\"inline-flex items-center gap-1 text-[#2c2e49] mx-2.5 text-sm no-underline transition-colors duration-300 hover:text-[#ff43a1]\"\n        >\n          "
      <> components_icons_frame.render(attributes: [
        runtime.Attribute("class", "mr-px text-[#ff43a1]"),
        runtime.Attribute("width", "15"),
      ])
      <> "\n\n          Core Framework\n        </a>\n        <a\n          target=\"_blank\"\n          href=\"https://gleam.run/\"\n          class=\"inline-flex items-center gap-1 text-[#2c2e49] mx-2.5 text-sm no-underline transition-colors duration-300 hover:text-[#ff43a1]\"\n        >\n          "
      <> components_icons_star.render(attributes: [
        runtime.Attribute("class", "mr-px text-[#ff43a1]"),
        runtime.Attribute("width", "15"),
      ])
      <> "\n\n          Learn Gleam\n        </a>\n      </div>\n    </div>\n  </div>\n"
    },
    attributes: [],
  )
  <> "\n"
}
