//// This file was generated by Glimr ✨
//// https://github.com/glimr-org/glimr?tab=readme-ov-file#loom
////
//// DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the
//// corresponding .loom.html template file and run `./glimr
//// loom:compile`.
////

import glimr/loom/runtime
import glimr/vite

pub fn render(
  slot slot: String,
  slot_footer slot_footer: String,
  slot_footer_scripts slot_footer_scripts: String,
  slot_head slot_head: String,
  slot_meta_title slot_meta_title: String,
  attributes attributes: List(runtime.Attribute),
) -> String {
  ""
  <> "\n<!doctype html>\n<html>\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n\n    <link\n      href=\"https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900\"\n      rel=\"stylesheet\"\n    />\n\n    "
  <> vite.tags("src/resources/ts/app.ts")
  <> "\n\n    <!-- header scripts and meta tags -->\n    "
  <> slot_head
  <> "\n\n    <title "
  <> " "
  <> runtime.render_attributes(attributes)
  <> ">"
  <> slot_meta_title
  <> "</title>\n  </head>\n  <body>\n    "
  <> slot
  <> "\n\n    "
  <> case slot_footer != "" {
    True -> {
      ""
      <> "<footer"
      <> ">"
      <> "\n      "
      <> slot_footer
      <> "\n    "
      <> "</footer>"
    }
    False -> ""
  }
  <> "\n\n    <!-- footer scripts -->\n    "
  <> slot_footer_scripts
  <> "\n  </body>\n</html>\n"
}
